language: c

compiler:
  - gcc

git:
  depth: 5

matrix:
  include:
    - os: linux
      services: docker
      script: docker run -v ${TRAVIS_BUILD_DIR}:/ptex-ng -w /ptex-ng -i -t ubuntu:18.04 sh -c "apt update; apt install -y texinfo texi2html gcc ruby make; ./build-gcc/build-aptex.sh"
    - os: osx
      osx_image: xcode10
      script: ./build-gcc/build-aptex.sh
