platform:
  - Any CPU
clone_depth: 10
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
build_script:
  - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'
  - cmd: cd build-msvc
  - cmd: set PATH=C:\Ruby25-x64\bin;%PATH%
  - cmd: build-mruby.bat
  - cmd: build-aptex-nmake.bat
test_script:
  - cmd: lsotfea.exe C:\Windows\Fonts\segoeui.ttf
  - cmd: aptex.exe -mrb-load-string "(1..20).each do |i| p i end"
